--RANK, ROW_NUMBER, DENSE_RANK

WITH T(StyleID, ID, A)
     AS (SELECT 1,1,1 UNION ALL
         SELECT 1,1,2 UNION ALL
         SELECT 1,1,3 UNION ALL
         SELECT 1,2,4 UNION ALL
		 SELECT 1,2,5)

SELECT *,
       RANK() OVER(PARTITION BY StyleID ORDER BY ID )       AS 'RANK',
       ROW_NUMBER() OVER(PARTITION BY StyleID ORDER BY ID  ) AS 'ROW_NUMBER',
       DENSE_RANK() OVER(PARTITION BY StyleID ORDER BY ID) AS 'DENSE_RANK'
FROM T 

